### ISSUE TITLE
ADMIN: Handle hard returns better

### ISSUE THREAD

**Issue by danxoneil** [smartchicago/connect-chicago-locator#26]
Example is the Friendly Description ("About this place") here: http://locations.weconnectchicago.org/location/pui-tak-center-2216-s-wentworth-avenue

It is all one paragraph. Using the admin tool, however, we can see that it is properly spaced:

![connect-chicago-admin-tool-spacing-issue](https://f.cloud.github.com/assets/100556/687329/205dd1e2-da78-11e2-81c6-d18250ceeb7b.png)

This will be important as we have the Summer of Data canvassers out and about.

**Comment by srobbin** [comment]
Looks like Keith already handled this in Commit 259b7cf0.
