### ISSUE TITLE
ADMIN: Image viewer is muffed; floats to top of screen out of view

### ISSUE THREAD

**Issue by danxoneil** [smartchicago/connect-chicago-locator#28]
Example, on Google Chrome: http://locations.weconnectchicago.org/location/canaryville-library-642-w-43rd-street
![screen shot 2013-06-25 at 8 36 53 pm](https://f.cloud.github.com/assets/100556/706994/c8d8547c-de07-11e2-81f6-0c1d4cf3b806.png)

And Safari:
![screen shot 2013-06-25 at 9 26 44 pm](https://f.cloud.github.com/assets/100556/706998/eb3d18ea-de07-11e2-8189-1aa3a38a35e5.png)

There's nothing magic about this viewer, so I'm open to a simple solution...

**Comment by danxoneil** [comment]
@keithgordon: any update on this?

I am open to a new solution. This might be a good place to start: http://www.flickr.com/services/apps/tags/viewer/

cc: @cgansen

**Comment by keiththecomputerguy** [comment]
I haven't found solution using the current image gallery. Looking for a new alternative

**Comment by derekeder** [comment]
This looks to be due to a negative margin being added dynamically via javascript. Removing it fixes the alignment.

![screen shot 2013-08-14 at 11 48 08 am](https://f.cloud.github.com/assets/919583/963355/6a6910c2-0501-11e3-9bf4-27f6ba098239.png)

Looks like a similar issue is happening in [this thread](https://github.com/jschr/bootstrap-modal/issues/115), with a fix included. 

If adding the stylesheet they mention doesn't work, [this looks to be an appropriate workaround](http://stackoverflow.com/questions/10363161/modal-plugin-of-bootstrap-2-is-not-displayed-by-the-center).

**Comment by keiththecomputerguy** [comment]
I followed the instructions in [this thread](https://github.com/jschr/bootstrap-modal/issues/115)

After moving bootstrap-image-gallery to a separate folder and adding
" *= require /image/boostrap-image-gallery.min.css" to the application.css

the images displayed correctly

**Comment by danxoneil** [comment]
Thanks for hopping in on this thread, @derekeder.

@keithgordon: I've tested this on Macbook in Chrome and FF, with cache cleared.

Problem persists.

![Uploading Screen Shot 2013-08-14 at 2.05.08 PM.png . . .]()
![Uploading Screen Shot 2013-08-14 at 1.36.35 PM.png . . .]()

**Comment by keiththecomputerguy** [comment]
@danxoneil  I also updated my twitter bootstrap (lastest version 2) javascript & css files

**Comment by danxoneil** [comment]
Closing this for now. If we do #30 and allow HTML in the admin, we can embed Flickr itesm and this will not be necessary any longer.

**Comment by srobbin** [comment]
So, this is what it looks like with an embedded Flickr slideshow:

http://images.srobbin.com/image/3U2J3F2n2c1q

The problem is, there's not a great way to hide the slideshow if no photos exist:

http://images.srobbin.com/image/1h15440p3n1Y

Either that, or I could just fix the lightbox.

**Comment by srobbin** [comment]
The site now uses a Flickr JavaScript slideshow:

http://locations.weconnectchicago.org/location/budlong-woods-library-5630-n-lincoln-avenue

Closed with Commit 775ab00..

**Comment by danxoneil** [comment]
It looks like the slideshow is hidden when there are no photos: http://locations.weconnectchicago.org/location/albany-park-library-5150-n-kimball-avenue, which is awesome. Is that right, @srobbin?

**Comment by srobbin** [comment]
Yeah, this plugin lets us check the number of photos before displaying the
slideshow. Right now, if there are zero photos, the slideshow is hidden.
Though, we can do whatever we like. e.g. Show a special message.

On Saturday, November 16, 2013, danxoneil wrote:

> It looks like the slideshow is hidden when there are no photos:
> http://locations.weconnectchicago.org/location/albany-park-library-5150-n-kimball-avenue,
> which is awesome. Is that right, @srobbin https://github.com/srobbin?
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/smartchicago/connect-chicago-locator/issues/28#issuecomment-28627791
> .

## 

## 

Scott Robbin
short: twitter.com/srobbin
long: srobbin.com

**Comment by danxoneil** [comment]
Nope, this is perfect as-is.
