### ISSUE TITLE
Items tagged in Flickr not appearing on location detail page

### ISSUE THREAD

**Issue by danxoneil** [smartchicago/connect-chicago-locator#3]
Yesterday evening I tagged a number of photos on Flickr with the "pccpoderlearningcenter181" tag: http://www.flickr.com/photos/juggernautco/tags/pccpoderlearningcenter181/

And one photo with the "pccpoderlearningcenter181featured" tag: http://www.flickr.com/photos/juggernautco/8475463132/in/set-72157632781587831/

None of these photos are showing up on the We Connect Chicago detail page: http://locations.weconnectchicago.org/location/poder-learning-center-1637-s-allport-st

One note: I first uploaded these photos as private a few days ago, then added titles, tags, and changed permissions to make them public yesterday. Not sure if that has anything to do with it, but worth mentioning...

**Comment by danxoneil** [comment]
Closed because the images are now loaded: http://locations.weconnectchicago.org/location/poder-learning-center-1637-s-allport-st

**Comment by derekeder** [comment]
The detail pages are cached for up to an hour for performance reasons. Because of this, there will be a slight delay from uploading/tagging in flickr to displaying on the site.

**Comment by danxoneil** [comment]
Definitely aware of how this feature works and that's why I waited before I tested and created the issue. Note the "Yesterday evening" phrase :-)

Derek, if you have any info on why the feature does not work as designed, that would be helpful. Otherwise, waiting a day for the items to be published is not the worst thing in the world...
