### ISSUE TITLE
ADMIN: Allow for HTML

### ISSUE THREAD

**Issue by danxoneil** [smartchicago/connect-chicago-locator#30]
There are a number of things we can do when HTML Is allowed in the admin tool.

1/ Flickr embeds, eliminating the need for #28 to be fixed.

2/ Slideshare embeds, like flyers showing hours: http://www.slideshare.net/juggernautco/truman-collegecomputerlab

**Comment by srobbin** [comment]
What do you think about something like this, where you can paste in a Slideshare embed code? (Ignore for a moment that it's referencing the wrong location)

http://images.srobbin.com/image/3j1O413t0210

Would you want the ability to name the section, or would something like "Additional media" suffice?

**Comment by srobbin** [comment]
There's now an "Additional media" content type at the bottom of the form. Added in Commit 42d6a43.

http://locations.weconnectchicago.org/location/harry-s-truman-college-1145-w-wilson
