### ISSUE TITLE
CSV seems to be failing

### ISSUE THREAD

**Issue by danxoneil** [smartchicago/connect-chicago-locator#34]
The process for generating the CSV necessary for the publication of this data on the City's data portal

For reference, the files is called, "connect-chicago-locations.csv"

**Comment by srobbin** [comment]
I updated [the script](https://github.com/smartchicago/connect-chicago-scripts/commit/fdfee80f9821505c31dc87a747db730ef37c56df#diff-22dcbc7cb73df10f6271b0d84652f9b5) to retry the FTP transfer 4 times, if failed.
