### ISSUE TITLE
Delete Locations / Remove bad information. 

### ISSUE THREAD

**Issue by GovInTrenches** [smartchicago/connect-chicago-locator#35]
As we go through the Wufoo survey, I may find locations that don't exist. (Or just bad information like this one: (http://locations.weconnectchicago.org/location/center-of-higher-development---englewood-6852-south-normal) 

Is there a way to delete the entry directly through the interface or do I need to go into the actual dataset and do it?

**Comment by danxoneil** [comment]
There is a delete button when logged in-- just make sure that it is actual gone...
![screenshot 2013-12-17 19 02 43](https://f.cloud.github.com/assets/100556/1770057/3237c748-6780-11e3-9b62-363674a56b6f.png)
