### ISSUE TITLE
How to change urls when name of center changes?

### ISSUE THREAD

**Issue by GovInTrenches** [smartchicago/connect-chicago-locator#43]
http://locations.weconnectchicago.org/location/leed-council-community-technology-center-1866-n-marcey-street 

They are now known as North Branch Works - the name is correct in Connect Chicago, but the URL is no longer in sync. Is there a way to change this through the interface, or do I need to go into the GitHub and do it?

**Comment by srobbin** [comment]
I think you'd have to do it directly in the Fusion Table. Do you have access to that?

**Comment by GovInTrenches** [comment]
I should - can you link me and I can test it?
-- 
Christopher Whitaker
Brigade Captain, City of Chicago
@CivicWhitaker

On May 5, 2014 at 1:10:59 PM, Scott Robbin (notifications@github.com) wrote:

I think you'd have to do it directly in the Fusion Table. Do you have access to that?

**Comment by srobbin** [comment]
https://www.google.com/fusiontables/DataSource?docid=1xy_wp4-NhtKPecuDlhsS8MLO0z-g5ayY1OfBhAg#rows:id=1

The `slug` column is the one that should be changed. Let me know if you'd like me to do it instead.

**Comment by GovInTrenches** [comment]
I can do it from my end. Can you grant christopherpaulwhitaker(at)gmail.com access to edit?
-- 
Christopher Whitaker
Brigade Captain, City of Chicago
@CivicWhitaker

On May 5, 2014 at 1:22:03 PM, Scott Robbin (notifications@github.com) wrote:

https://www.google.com/fusiontables/DataSource?docid=1xy_wp4-NhtKPecuDlhsS8MLO0z-g5ayY1OfBhAg#rows:id=1

The slug column is the one that should be changed. Let me know if you'd like me to do it instead.

**Comment by srobbin** [comment]
Oy, it looks like I don't have permissions either. 

@cgansen: Do you have ownership rights to the Connect Chicago fusion table? Or is that Derek's?

**Comment by cgansen** [comment]
IIRC it's owned by the smartchicago2012@gmail.com address.

On Mon, May 5, 2014 at 1:47 PM, Scott Robbin notifications@github.comwrote:

> Oy, it looks like I don't have permissions either.
> 
> @cgansen https://github.com/cgansen: Do you have ownership rights to
> the Connect Chicago fusion table? Or is that Derek's?
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/smartchicago/connect-chicago-locator/issues/43#issuecomment-42222934
> .

## 

http://www.chrisgansen.com/

**Comment by srobbin** [comment]
@smarziano Do you have access to the smartchicago2012@gmail.com account? If so, can you please find me on Gchat?

**Comment by srobbin** [comment]
@GovInTrenches What do you want the URL changed to? I should be able to do this from the command line.

**Comment by GovInTrenches** [comment]
Lets go with http://locations.weconnectchicago.org/location/North-Branch-Works-community-technology-center-1866-n-marcey-street

Thanks! 

-- 
Christopher Whitaker
Brigade Captain, City of Chicago
@CivicWhitaker

On May 6, 2014 at 11:02:01 AM, Scott Robbin (notifications@github.com) wrote:

@GovInTrenches What do you want the URL changed to? I should be able to do this from the command line.

**Comment by srobbin** [comment]
Got it. The account was associated with another Gmail address, techlocator@gmail.com. I gave us edit privileges, and changed the slug. That link should work now.
