### ISSUE TITLE
Error on reaching location page

### ISSUE THREAD

**Issue by GovInTrenches** [smartchicago/connect-chicago-locator#44]
Hi Scott, 

Whenever I try to access a location on the location page, it errors with the following message: 

"Error
Oops! There was an error.
Go back and try again.

If this issue persists, contact the system administrator. " 

Can you take a look? 
Thanks

**Comment by srobbin** [comment]
Yep. I'll take a look now.

**Comment by srobbin** [comment]
This should be fixed now. Let me know if you notice anything else.

**Comment by GovInTrenches** [comment]
![image](https://cloud.githubusercontent.com/assets/1302753/3447113/d6c3de2e-0149-11e4-8080-85582bd1f2b1.png)

I received this error. I attempted it again and was successful in creating a location: http://locations.weconnectchicago.org/location/center-for-changing-lives-in-logan-square-3051-w-armitage-ave - but wasn't sure what caused the error.

**Comment by srobbin** [comment]
This looks like a different problem than the Flickr one. For some reason, Fusion Tables coughed up and error message while you were creating a new record:

> "error": {
> 2014-07-01T17:59:51.536709+00:00 app[web.1]:     "domain": "fusiontables",
> 2014-07-01T17:59:51.536711+00:00 app[web.1]:     "reason": "badQueryCouldNotParse",
> 2014-07-01T17:59:51.536728+00:00 app[web.1]:   ],
> 2014-07-01T17:59:51.536712+00:00 app[web.1]:     "message": "Invalid query: Parse error near ',' (line 1, position 1358).",
> 2014-07-01T17:59:51.536714+00:00 app[web.1]:     "locationType": "parameter",
> 2014-07-01T17:59:51.536726+00:00 app[web.1]:    }
> 2014-07-01T17:59:51.536731+00:00 app[web.1]:   "message": "Invalid query: Parse error near ',' (line 1, position 1358)."
> 2014-07-01T17:59:51.536724+00:00 app[web.1]:     "location": "q"
> 2014-07-01T17:59:51.536734+00:00 app[web.1]: }
> 2014-07-01T17:59:51.536735+00:00 app[web.1]: 
> 2014-07-01T17:59:51.537558+00:00 app[web.1]:  /app/vendor/bundle/ruby/1.9.1/gems/fusion_tables-0.4.1/lib/fusion_tables/data/table.rb:83:in `rescue in block in insert'
> 2014-07-01T17:59:51.536732+00:00 app[web.1]:  }
> 2014-07-01T17:59:51.536729+00:00 app[web.1]:   "code": 400,

If it happens again, while you're creating a new location, open a new Issue. It think we've nipped the Flickr problem in the bud.
